### ISSUE TITLE
Easy Find in Page

### ISSUE THREAD

**Issue by Coder206** [browserhtml/browserhtml#1083]
To simplify search on a current webpage, I think it would be more intuitive if you could just start typing and browserhtml starts finding all the matches for the text input. The code would activate when there is no focus on other text field elements. This allows a search in page experience similar to Fedora 23 where this concept is used when searching for programs.

**Comment by Gozala** [comment]
@Coder206 there is a bug for searching adding search in page in first place #163 once that is fixed we can consider this. That being said, I used to have that feature enabled for firefox and soon enough run into issues with various sites that were they would handle keybindings while firefox would also search in page, so I have doubts about this feature honestly.

**Comment by Coder206** [comment]
@Gozala I agree, I am having trouble with it too.

**Comment by paulrouget** [comment]
> I have doubts about this feature honestly.

That would be pretty hard to get right, indeed. Even with the `/` prefix, it's already broken in many websites with Firefox.

**Comment by Coder206** [comment]
How about we use the address bar to find in page. Simply type everything inside that bar...

**Comment by tschneidereit** [comment]
> How about we use the address bar to find in page. Simply type everything inside that bar...

How would you differentiate between in-page searches and online searches/URL input? Those last two already overload how the input is interpreted - searching within the page would add another dimension and is, I think, way too much.

**Comment by Coder206** [comment]
@tschneidereit It depends how it is being implemented... Give me a moment to make a UI mockup to show you what I mean.

**Comment by Coder206** [comment]
Here is a simple UI for addressing this issue, would love to hear comments about it:

![findinpage_mod](https://cloud.githubusercontent.com/assets/7758155/16522703/5fbab3de-3f6d-11e6-9f08-9603f16abb14.png)

**Comment by tschneidereit** [comment]
That means that every in-page search hits the network first, and you can't just start entering a string to search for and immediately see results highlighted on the page. Both of these are deal breakers.

**Comment by Coder206** [comment]
@tschneidereit What do you mean by "hits the network first"?

**Comment by tschneidereit** [comment]
If I understand your proposal correctly, you'd first enter your search string into the location bar and then press "Find in Page", right? Up to the point where you press the "Find in Page" button, we'd assume that you want to navigate somewhere, so we'd load suggestions. Now you could say that we just shouldn't do that and instead require a second "Find Online" button, but then we're talking about a much more substantial UX change. And one that people would definitely not like, I'm pretty sure. It also doesn't address the second issue I described above.

**Comment by Coder206** [comment]
@tschneidereit Correct when you mentioned "Find in Page". As for "Find Online", I don't like that idea, I believe the search suggestions should remain as presented above.

The proposal is just: Adding a option in the drop down of the address bar called "Find in Page" to allow a user to find text inside a webpage.

**Comment by tschneidereit** [comment]
> The proposal is just: Adding a option in the drop down of the address bar called "Find in Page" to allow a user to find text inside a webpage.

Understood. But that means that every attempt to find something within the current page will have to send your search to the network, too.

**Comment by Coder206** [comment]
@tschneidereit Is that because the address bar always sends it's content through the network?

**Comment by tschneidereit** [comment]
How else would it should search suggestions?

The fundamental problem is this: when searching for something, the natural approach is to start typing and choose a matching suggestion as soon as it appears. Say you want to search for `mozilla`, so you start typing `moz`. At that point, we'll already show search suggestions that are quite likely to match, so you can stop typing. This is important for usability, especially for longer queries.

Now the same is true when searching within a page: you shouldn't need to first complete your full search query - in this case `mozilla` - before saying "now find that in the page". So it's important to immediately react to search input for that case, too.

Here's a more complex example where it should be obvious why this is important. Say you remember that somewhere on servo.org, there's a description of which commandline arguments are supported. Instead of scrolling through the page until you find the info, you want to search for it. With your proposal, you'd have to enter the full query. Now what was it again, "commandline arguments", or "command line arguments" (note the added space)? If you can just start typing and see results immediately, it doesn't matter, as you're very likely to see the correct result after typing "command" (or even "comma"). You can also easily fix your query without having to explicitly confirm it again.

**Comment by tschneidereit** [comment]
Here's another issue: after pressing "Find in Page" and then dismissing the location bar, what if you want to search for the same term again, or change the query? If you click on the location bar again, it displays the page's location, not your last search. (It should, at least. If it doesn't, the opposite question becomes relevant: how do you get to the page's location after searching within the page?)

Again, this overloads the location bar in a way that just doesn't work, I'm afraid.

**Comment by Coder206** [comment]
@tschneidereit I understand your concern!

**Comment by Gozala** [comment]
We were actually going to use our omni input field for search in page, for executing commands and more. @gordonbrander has done UX & specification work for all of this, specifically to address issues @tschneidereit pointed out.

You can find specs & mocks in the existing issues

**Comment by Coder206** [comment]
@Gozala I can't seem to find @gordonbrander's specs and mocks in the issues. Do you mind pointing that out for me?
