### ISSUE TITLE
No dwelling on the past (for tabs)

### ISSUE THREAD

**Issue by Coder206** [browserhtml/browserhtml#1117]
Browser.HTML is showing an old tab in the mean time the new one is loading. It's a little awkward when waiting for the new tab to show up - if it ever does.

**Comment by tschneidereit** [comment]
That's what all browsers do. Turns out the perceived page load time is longer if you don't show anything, or a loading spinner, until the page has loaded enough to render it. The only reason this is somewhat bad in Servo/browser.html right now is that the network layer and disk cache aren't fully optimized yet and so the load takes longer than in other browsers.

I'll close this, as we don't plan on changing the behavior here (except for making things faster).
