### ISSUE TITLE
New tab order.

### ISSUE THREAD

**Issue by mason-larobina** [browserhtml/browserhtml#1162]
Opening a new tab counter-intuitively places the new tab index at 0.

For example with the following tabs open and tab index 1 active:

```
0: google.com
1: reddit.com [active]
```
Pressing `Ctrl+T` (open new tab) results in:

```
0: new-tab [active]
1: google.com
2: reddit.com
```

And a subsequent `Ctrl+W` (close tab) does nothing.

I would have expected the following behaviour on `Ctrl+T`:

```
0: google.com
1: reddit.com
2: new tab [active]
```

And `Ctrl+W` to return to the original state:

```
0: google.com
1: reddit.com
```

Thanks!

(Moved from https://github.com/servo/servo/issues/12177)

**Comment by Gozala** [comment]
@mason-larobina thanks for the feedback. I am afraid current behavior is expected one. In this UX we are trying to get rid of some of the pre-existing notions like bookmarks, history, new tab. In the current UX 
`New Tab` is a special tab that is always at the top off the list and you can't close. There is no opening new tab, there is switching to `New Tab`. Order of tabs most recent on the top is also by design. Idea that in future we will have infinite scroll view of tabs and placing things on top of that list makes more sense than at the bottom.

Unfortunately current UX implementation is incomplete so it may seem odd at a times. We hope to improve on that over time & for now we're trying to not lock ourselves into expectations that users have built up using pre-existing browsers.

Hope this helps a bit.
