### ISSUE TITLE
Write specification for scrolling right past page content

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#1255]
Spec for http://patrykadas.me/mex/previous

**Comment by patrykadas** [comment]
Back transition animation:
https://www.youtube.com/watch?v=A8YoaE-gMg8
For the purpose of animation I have used longpress & drag, because Framer does not support trackpad really well, however our trigger is swipe with two/three fingers.

Rubber Effect Framer example:
http://share.framerjs.com/xnmvnegqczg1/
As above, it works with longpress + drag.


[specification.pdf](https://github.com/browserhtml/browserhtml/files/526780/specification.pdf)

**Comment by paulrouget** [comment]
Thanks for putting all of that together. Some comments:

General comment:

I think you should not use width percentages as reference for opacity and scale changes. That would change the snap threshold depending on the browser size. I would use absolute pixels, and percentage of that threshold to define opacity and scale.

Page 2:

> If the previous page is released before reaching the limit the current page pops back

What do you mean "page is released"? Does it include the momentum scroll? Or just when the user releases his fingers from the trackpad?

Page 3:

> 50% opacity of the URL

What is "50% opacity of the URL"?

> accidental drag

When do you think this might happen?

Scroll events are "direction locked". Meaning that a horizontal scroll only happens if the user actually is doing a flat horizontal scroll (diagonal scroll won't trigger it).

Page 9:

I think we should use what ever OSX values are. It would be weird to have a different rubber effect in Servo compared to other apps.

**Comment by patrykadas** [comment]
> I think you should not use width percentages as reference for opacity and scale changes. That would change the snap threshold depending on the browser size. I would use absolute pixels, and percentage of that threshold to define opacity and scale.

You are right, that's a good point - I am still used to designing pages I guess. 

> What do you mean "page is released"?
Swipe is released, you stop touching trackpad. 

> What is "50% opacity of the URL"?
Opacity of the URL box in navigation bar is changing, as seen in video. 

> Scroll events are "direction locked". Meaning that a horizontal scroll only happens if the user actually is doing a flat horizontal scroll (diagonal scroll won't trigger it).

Ok, that's clear then. 

>I think we should use what ever OSX values are. It would be weird to have a different rubber effect in Servo compared to other apps.

I agree, I thought we have to define our own values. 

I also agree with @Gozala comment:
> I’m little worried about slow swipe vs fast swipe, because initial speed is not necessarily going to be the general speed. What if you accelerate later, or you started off too fast

...and before going with final documentation I wanted to experiment with different swipe options to combine both scenarios and here's what I came up with so far:
https://www.youtube.com/watch?v=VfGWyKFPYdM

**Comment by paulrouget** [comment]
Thanks for the comments.

> Swipe is released, you stop touching trackpad.

Just to be clear: scroll events still happen even though your fingers are not on the trackpad anymore. When you release your fingers, there is inertia, and some more events still happen until the delta reaches 0. These are scroll "momentum" or "fling" events.

**Comment by Gozala** [comment]
> Back transition animation:
> https://www.youtube.com/watch?v=A8YoaE-gMg8
> For the purpose of animation I have used longpress & drag, because Framer does not support trackpad really well, however our trigger is swipe with two/three fingers.

IMO Safari does one neat thing that I would like to carry over, which is while there is a threshold unless you release fingers page won't slide out. That is really helpful if you want to take a pick at previous page but don't like to actually go back. In summary:

1. If you release fingers pass threshold and previous page is sliding forward it will slide over current page (go back happens).
2. If you release fingers pass threshold but previous page is sliding backwards it snaps back and you stay on current page (go back does not happen).
3. If you release fingers pre threshold previous page snaps back and you stay on current page (go back does not happen).

**Comment by Gozala** [comment]
# Decoupling titlebar from history entries

I do not like this direction because I see titlebar as part of each entry. For example if we end up (and I hope we will) displaying a grid in the "overview" (view with sidebar open) then you'd want to display titles of each entry attached to them. But if you change model to single titlebar per tab then that does not fit as well. There is also a thing with color matching, titlebar does matches page content so it may be of different color across different history entries. I also was hoping to blur lines  between history entries and tabs but by sharing a titlebar across tab entries we emphasize difference.

Than being said I do like idea of indicating that you are "going to" previous / next page vs just trusting your intuition. Proposed indicator is subtle enough though that it's easy to miss. I did miss it in fact. Not sure if that feature necessarily requires sharing titlebar across entries. Is there some better way to indicate this ?

# Return to rather then go back to

> ...and before going with final documentation I wanted to experiment with different swipe options to combine both scenarios and here's what I came up with so far:
https://www.youtube.com/watch?v=VfGWyKFPYdM

I like direction of where it's headed not necessarily current rendering though seen in the video, mostly because you get poor overview of pages you can return to. I think I preferred the original rendering where pages were scaled down and one to be activated was slightly larger that gave a better overview of available options IMO. Also gave better indication what is being activated right now. Finally I think it fit better with a grid layout in the "overview" mode. 

# Rubber Effect

Do we actually need rubber effect or do we just follow the cowpath. I suspect later as other than giving us more physical world feeling it provides nothing to the user. I think we could do better! What if we did slightly altered version of "Return to" interaction and just unfolded all entries, would not that be more useful ? If you think about it when you try to go back and there is nothing in the back most likely you trying to find a page to "return to" so giving you an overview of what's there is far more useful IMO than just indicating there's nothing in the back. Alternatively we could go full blown "overview" mode - unfold entries and show sidebar with all entries as a grid and newtab to start fresh. There would have to be a smart threshold of course to not make it annoying, but I think sliding over sidebar as you swipe will be a good enough indicator that you're reached the end. Maybe sidebar should be on the left side that way you'd see sidebar instead of nothing on the left of current page.

**Comment by patrykadas** [comment]
> Decoupling titlebar from history entries

I agree with most, I wanted to detach it, as there are going to be interface elements that corelates strictly to the browser (switching to "overview mode" is not a page's attribute), but actually we can just decouple those elements, leaving titlebar as element of page. 

>Return to rather then go back to

I agree and I am working on it. 
![too](https://cloud.githubusercontent.com/assets/6234032/19449675/d8d218c8-94a6-11e6-9b5d-ee7dfe1ada50.jpg)

> Rubber effect
Ok, I think that here it's more tricky. I agree with your comment, however I would like to make it a two-step interaction (swipe -> swipe harder), as I've observed many people just playing around with this effect and that was my main reason to follow cowpath.

> Anchor links

I need to think more about this issue, as currently I have no other idea rather than displaying an alert / info box.

**Comment by Gozala** [comment]
> Ok, I think that here it's more tricky. I agree with your comment, however I would like to make it a two-step interaction (swipe -> swipe harder), as I've observed many people just playing around with this effect and that was my main reason to follow cowpath.

Do you think placing sidebar to the left would help here ?

**Comment by patrykadas** [comment]
> Do you think placing sidebar to the left would help here ?

I don't think that the position of the sidebar (left - right) is relevant here, as long as it is expanded it gives clear message that there is no page behind nor forward.

**Comment by patrykadas** [comment]
https://www.youtube.com/watch?v=F9WfIpKakZk

This is the visualization of back functionality. At first, user is able to glance at previous page, but if user keeps scrolling, we zoom out the whole container.
