### ISSUE TITLE
Search in-page

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#163]
This should be a token that lives in the search box.

**Comment by paulrouget** [comment]
There are dozen of ways to search in a page in Gecko. Different interfaces, JSMs, helpers, messages, XBL methods, (depends on the platform, Android, Firefox Desktop, Firefox Desktop E10S). There's even a JS method accessible from content (`window.find()`).

We can't re-use most of the existing helpers because they are tight to `browser.xml` (XBL).

I'd suggest that we use `nsITypeAheadFind`.

**Comment by paulrouget** [comment]
Let's use the same API as Android:

> findAllAsync(string term)
> findNext (boolean forward)
> clearMatches()
> "mozbrowserfindresult"
>   . activeMatchOrdinal
>   . numberOfMatches

**Comment by paulrouget** [comment]
Changing my mind. I recommend to fix `Finder.jsm` to make it work in non-XBL browsers.

**Comment by paulrouget** [comment]
Platform patch in progress: https://bugzilla.mozilla.org/show_bug.cgi?id=1163961

**Comment by paulrouget** [comment]
The patch is about to land.

The API will look like this:

> enum BrowserFindCaseSensitivity { "case-sensitive", "case-insensitive" };
> enum BrowserFindDirection { "forward", "backward" };
> void findAll(DOMString searchString, BrowserFindCaseSensitivity caseSensitivity);
> void findNext(BrowserFindDirection direction);
> void clearMatch();

Event:

> mozbrowserfindchange({
>   active: true,
>   searchString: 'foo',
>   searchLimit: 100,
>   activeMatchOrdinal: 1,
>   numberOfMatches: 5
> })

**Comment by paulrouget** [comment]
Patch has landed. Now we need the frontend. Assigning @Gozala.

**Comment by Coder206** [comment]
@gordonbrander Are you proposing a secondary search bar for searching inside a page?

**Comment by Gozala** [comment]
@Coder206 interaction is described in the wireframes document:

https://drive.google.com/open?id=0B1az_KF0ZYc_bzIyZzJRTm4tZVk

**Comment by Coder206** [comment]
@Gozala Very good. Thanks :)

**Comment by Coder206** [comment]
@Gozala That interaction seems to be most ideal. :)

**Comment by Gozala** [comment]
> @Gozala That interaction seems to be most ideal. :)

Document does not seem to say it but intention was that `CMD F` would just focus input bar with `page: ` pre-entered so you can just type in the term to search in page.

**Comment by Coder206** [comment]
@Gozala Exactly, I find the `page:` idea most intuitive to get this working.

**Comment by Gozala** [comment]
I still have my resurrections with the fact that until you reach `:` character we'll be querying search engine with what you typed. But we might come up with some solution to fix this.

**Comment by Coder206** [comment]
@Gozala I noticed "-page" yields very little results on Bing. Could this be a way to solve your concern? (where browserhtml automatically searches in page when the first character is "-" and is followed by "page")

**Comment by Gozala** [comment]
> @Gozala I noticed "-page" yields very little results on Bing. Could this be a way to solve your concern? (where browserhtml automatically searches in page when the first character is "-" and is followed by "page")

I was suggesting to go with `:page`, `:go back`, `:reload` etc. as a way to hook in commands. That way from the first character we could decide weather user wants to run command (in fact suggest available commands you user types) or search the web. @gordonbrander had resurrections though due to being too engineer minded and less humane.

What we learned working through different interactions though, is what may sound cool on paper may or may not work in usage. So I think we'd have to prototype several interactions and find out what works best.

**Comment by Coder206** [comment]
@Gozala Funny, after coming up with ":page" too, I thought of it and came to the same conclusion as @gordonbrander
