### ISSUE TITLE
ContextMenus

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#29]
Can we already use [HTML5 ContextMenu](https://html.spec.whatwg.org/multipage/forms.html#the-menu-element) API implement context menus in browser ? If not I'd be willing to hack a support for that in runtime until we get something more proper in platform.

**Comment by paulrouget** [comment]
There are different things. Building the native panel. Opening the menu on time. Populating the menu with `<menu>` content. Populating the menu with browser controls (save, back/fwd, view page source, ...).

No limitation here afaik.

Let's just no use xul to open the panel.

**Comment by andreasgal** [comment]
Context menus are an artifact of the last millennium and of 2nd mouse buttons. Do we really need them?

**Comment by andreasgal** [comment]
(In a touch age)

**Comment by paulrouget** [comment]
> Context menus are an artifact of the last millennium and of 2nd mouse buttons. Do we really need them?

No.

**Comment by johancz** [comment]
Not needed as in, not necessary for this (browser.html) proof of concept?

**Comment by andreasgal** [comment]
Not needed as in if we reimagine a browser from scratch for the year 2015, then today we probably wouldn't build context menues into the browser.

**Comment by johancz** [comment]
> Context menus are an artifact of the last millennium and of 2nd mouse buttons. Do we really need them?

What makes context menus artefacts? And what is wrong the second mouse button?

> (In a touch age)

Touch is hardly superior, in many cases it is inferior.

> Not needed as in if we reimagine a browser from scratch for the year 2015, then today we probably wouldn't build context menues into the browser.

Are we talking about the same thing here? Many browsers were built from scratch for touch devices, and because they are essential components, these browsers have plenty of context menus.

Your statements are making me thoroughly confused. :(

**Comment by donaldpipowitch** [comment]
> Not needed as in if we reimagine a browser from scratch for the year 2015, then today we probably wouldn't build context menues into the browser.

Same question here: Why? Why is this so archaic? What is a better way to do this in your opinion? E.g. you see a nice image on a website and want to download it. I guess most people would try to right-click-it and choose "Save image...".

**Comment by paulrouget** [comment]
What we don't want to do is to add a context menu just because browsers always had context menus.

Better do it the other way around: Why do we need a context menu? Are these things still valid today (see all the never-used items in a context menu)? Then, what's left? Saving images, probably. Some more things (sharing & co). Then, is a context menu the best answer?

Just reconsidering all the assumptions.

**Comment by past** [comment]
(Hamburger) Menu buttons in the UI and long press gestures are two of the most common replacements in touch UI nowadays.

**Comment by donaldpipowitch** [comment]
> long press gestures are two of the most common replacements in touch UI nowadays

Yeah, this is fine with touch, but I would guess saving an image with a right click is so universal for most users that even if there is a better/faster alternative for desktop, I would implement a context menu as well, so most users aren't confused about how to save an image. 
I think a good UX isn't only about choosing the _best way_ to reach a goal, but to offer multiple ways so _most_ (because _all_ isn't possible) users have a satisfying experience. And _satisfying_ is subjective  here: it could mean to reach a goal very fast for one user and to reach it very easily and convenient for someone else. It's like offering hotkeys/shortcuts or a CLI for powers users as well as a menu bar with menu items and a GUI in general for others.

So to answer the questions from my point of view:
> Why do we need a context menu?

It's a convenient pattern understood by most users.

> Are these things still valid today (see all the never-used items in a context menu)? Then, what's left? Saving images, probably. Some more things (sharing & co).

I personally use "Copy address from link" very often as well as items from my Browser extensions (e.g. "Save to Pocket"). And of course "Find Element" as a developer.

> Then, is a context menu the best answer?

Maybe not, but I don't think this is the right question. Maybe "Do the benefits outweigh the cons?" is better. And I would answer this with "Yes".

**Comment by paulrouget** [comment]
> (Hamburger) Menu buttons in the UI and long press gestures are two of the most common replacements in touch UI nowadays.

This is not a reason to use them.

> It's a convenient pattern understood by most users.

Same.

> Maybe not, but I don't think this is the right question. Maybe "Do the benefits outweigh the cons?" is better. And I would answer this with "Yes".

Right. Expectations.

Again… here we are just taking a step back. Reconsidering everything. Asking the questions. Not taking decisions.

**Comment by donaldpipowitch** [comment]
So if I understand you correctly "a convenient pattern understood by most users" "is not a reason to use [it]". Don't get me wrong: choosing a context menu should _not_ block the search for a better UX pattern. It is just an alternative and I think something which is convenient for a lot of users is a very good reason to choose something - at _least_ as an alternative. Everything else would confuse users even if there many more better ways. These solutions can and should work in parallel to each other.

Could you please explain me the goals of browser.html? Should I challenge the status quo in every single way or should it create a solid user experience? If it is just for exploring new UX patterns, we can drop a context menu, but if the latter is true, I doubt we can drop context menus. I don't want to be seen narrow-minded here, I'm just convinced that context menus are very useful for a lot of users and don't conflict with better patterns.

**Comment by paulrouget** [comment]
> They would be disappointed if they look for a context menu and can't find one.

Yes.

> Should it challenge the status quo in every single way or(/and) should it create a solid user experience (~ a solid browser with web technology)?

Both. We try stuff. See how it feels. Iterate.

**Comment by PalmerAL** [comment]
You should be able to right click and get commonly used actions, for two reasons:
- users are used to it, and you should not try to force change on users unless there is a good reason.
- on large displays, having frequently needed buttons at the very top in a toolbar gets annoying.

That being said, there is no reason the context menu has to work like a regular context menu, and in many ways it shouldn't. Maybe a grid of icons like the firefox menu or the ios share sheet?

Things that should be in the context menu are:

-define (when a word is highlighted). Most things don't have this, but they should. It is extremely useful.
-save image
-open link in new tab
-bookmark page
-back/forward

Also, since what functions are useful is different to everyone, it would be interesting to extend the customization UI to the context menu.

**Comment by Gozala** [comment]
Doing nothing at all on right click will be just confusing to users. Also there is HTML context menu API do we just don't care about that ?

**Comment by paulrouget** [comment]
> Doing nothing at all on right click will be just confusing to users

We can do something. Not sure what yet. Doesn't hurt to add a placeholder menu. Gordon might have ideas.

**Comment by Gozala** [comment]
servo/servo#7083

**Comment by Gozala** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1198495
