### ISSUE TITLE
ToolbarMenu

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#30]
At the moment toolbar menu is hard coded into a runtime https://github.com/mozilla/browser.html/blob/master/runtime/shell.xul#L82

This is not ideal, I think we should use [HTML5 `<menu type="toolbar">`](https://html.spec.whatwg.org/multipage/forms.html#the-menu-element) in the app itself to populate OS toolbar menu.

We could use mutation observers in order to track changes to a toolbar to repopulate `<menubar id="main-menubar">` in the `shell.xul` & re-trigger events in the app document.

@zer0 did something along these lines in a past so we could likely integrate that work here.

**Comment by paulrouget** [comment]
I'd prefer to not use a xul menubar, but build it in C++.

**Comment by paulrouget** [comment]
Do we actually need a toolbar?

**Comment by andreasgal** [comment]
Toolbars suck. The Web doesn't use toolbars.

**Comment by paulrouget** [comment]
I'll build a menu item to quit the app, like in any osx app.

**Comment by donaldpipowitch** [comment]
> Toolbars suck. The Web doesn't use toolbars.

> Do we actually need a toolbar?

Sounds like the same discussion as in ContextMenus. Why do they suck? There are convenient and easy to use. Are they perfect? No. Could they be added even alongside a better solution without conflicting with the better solution, just because many people are used them? Possibly.

What would be a better solution? Can't we use toolbars as long as we don't have something better? Even if we have something better, maybe we can keep both or let the user decide which they want to use (at least power users).

I don't mind a healthy discussion, but because of missing solutions it seems wrong to not use toolbars for now.

**Comment by paulrouget** [comment]
I added the `Quit` item. Anything else we really need?

**Comment by Gozala** [comment]
With all due respect I expect apps on OSX to have toolbar with common menus like `File`, `Edit`, `View`, `Window`  and `Help`. I image most users on OSX would expect to have at least those menus.

**Comment by paulrouget** [comment]
> I imagine most users on OSX would expect to have at least those menus

I believe it's the opposite. But having a bar won't hurt (I already added the `quit` button there). This is absolutely not a priority.

**Comment by Gozala** [comment]
servo/servo#7083

**Comment by Gozala** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1198495
