### ISSUE TITLE
Many rendering take more than 15ms

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#653]
See the console.

**Comment by Gozala** [comment]
I have briefly looked at it and assumed it was caused by #624. I also did some research and most likely it's not it. While doing so I noticed that we end up with dev version of react vs production version of react due to our build process which could be a reason. I briefly looked at a fix but could not get it to work, will investigate more once done with current milestone.

If production react version does not resolve this then I'd really like to do #633 so reasons for long renders can be more easily investigated and traced.
