### ISSUE TITLE
Create mozilla.github.io/browserhtml

### ISSUE THREAD

**Issue by gordonbrander** [browserhtml/browserhtml#793]
We should create a splash page for the project.

**Comment by gordonbrander** [comment]
First-pass sketch ![artboard 1 copy 18](https://cloud.githubusercontent.com/assets/58421/12133599/9b73b60a-b3db-11e5-8459-554c2db1847a.png)

**Comment by gordonbrander** [comment]
(the screenshot in the browser is TBD... we should animate it)

**Comment by Gozala** [comment]
Should we just repurpose http://mozilla.github.io/browser.html/ ? We could use `http://mozilla.github.io/browser.html/main.html` or something like that for actual browser.

**Comment by gordonbrander** [comment]
I think it might make more sense to create a GH organization so we can have multiple repos (browser, website, libraries). I've registered https://github.com/browserhtml.

**Comment by Coder206** [comment]
I am interested in helping to build this website.

**Comment by Gozala** [comment]
@Coder206 Thanks! Our goals have shifted since we originally started this project / issue. Given our current focus I am not exactly sure if we need separate website from servo.org or not. Maybe we do or maybe we can improve servo.org. I'll make sure to discuss this with the team so we can figure out what to do here.

P.S.: Unfortunately most of the team is going to be on vacations in coming weeks so it may take a while. I'll make sure to update this issue once we get a chance to discuss.

**Comment by Coder206** [comment]
@Gozala Ok perfect thanks.

**Comment by paulrouget** [comment]
A browserhtml specific landing page would be confusing.
