### ISSUE TITLE
Integrate error pages

### ISSUE THREAD

**Issue by joshua-s** [browserhtml/browserhtml#884]
We need to handle server/network errors with simple, useful error pages.

**Comment by paulrouget** [comment]
There are a lot of possible error: http errors, network error (can't reach server), ssl/cert error, crash, too many redirect, …

In theory (haven't tested), gecko-Graphene handles these in 3 ways:
- http error: nothing to do (the message is part of the http response, 404 for example)
- other error: either `net_error.html` is loaded or we get a mozbrowsererror: https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowsererror

I'm not sure what happens when.

**Comment by paulrouget** [comment]
@gordonbrander Do we want to support that by June?

**Comment by paulrouget** [comment]
@gordonbrander ping?

**Comment by gordonbrander** [comment]
@paulrouget I wouldn't block on it.

**Comment by Coder206** [comment]
@gordonbrander @paulrouget Is there anything I can help out with here?

**Comment by paulrouget** [comment]
I think we want to wait the Browser API v2 to understand how this will work.

**Comment by Coder206** [comment]
@paulrouget Alright!
