### ISSUE TITLE
servo+browser.html - entering an url in the url bar doesn't seem to work after navigating a page

### ISSUE THREAD

**Issue by nical** [browserhtml/browserhtml#949]
Not sure whether it belongs to servo or browser.html. On a local build of [today's servo](https://github.com/servo/servo/commit/4341dc5fb45a3e4d5397ca64e7aabe85f8ac23ab) on Linux:

1) ./mach run --release -w -b
2) enter reddit.com/r/rust in the url bar and press enter
3) visit a link from the reddit page
4) enter reddit.com/r/rust again in the url bar
5) nothing happens

**Comment by paulrouget** [comment]
Yeah. Most likely https://github.com/browserhtml/browserhtml/pull/948

**Comment by Gozala** [comment]
This is not fixed by #948 as far as I can tell.

**Comment by Gozala** [comment]
Ok, it seems to be related to the VirtualDOM stuff. Problem is we do not touch 'src' when location changes, because if did that would cause a page load. So what happens is that we change src back to what it was, then when VirtualDOM does diff / patch it can see that `src` attribute hasn't changed  so it does not `setAttribute('src', url)` and there for load does not occur. 

I need to think about this problem, but I'm going to submit a patch to fix this on way or another.
