### ISSUE TITLE
Npm install fails on Windows

### ISSUE THREAD

**Issue by Jayflux** [browserhtml/browserhtml#964]
Node v4.4.0
npm v3.4.1
https://gist.github.com/Jayflux/e051491cc788e17c420a

@paulrouget  have you tried running this on windows?

**Comment by paulrouget** [comment]
I did not. @Gozala any idea what's going on?

**Comment by Gozala** [comment]
As far as I can tell from logs issue is related to `graphene-marionette-client` package that has being very unstable (on all platforms) dependency of ours for running tests. That being said it is no longer listed in our dependencies, as I removed it given that we are focused on servo anyhow and we were not using this tool but paying cost for it's instability. We might reintroduce that dependency in a future (hopefully it'll be more stable then) but for now it's gone.

@Jayflux Please try installing again & report if it's still not working.

I'll close this one since reason install was failing is now obsolete.
